version: "3.9"

services:
  db:
    image: mysql
    container_name: mysql_portafolio
    ports: 
      - "3306:3306"
    networks:
      - api-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_USER: ${DB_USER} 
      MYSQL_DATABASE: ${DB_DATABASE} 
      MYSQL_PASSWORD: ${DB_PASSWORD} 
    
networks:
  api-net:
    driver: bridge
