FROM node:16.13.1

RUN mkdir -p /usr/src/api

WORKDIR /usr/src/api

COPY package.*json /usr/src/api/

RUN yarn install

COPY . /usr/src/api/

RUN yarn build

COPY ./src/public/email/email.html /usr/src/api/dist/public/email/
