version: "3.9"

services:
  api:
    container_name: api_portafolio
    build:
      context: ./
      dockerfile: dockerfile.dev
    depends_on:
        - db
    volumes:
        - "./:/usr/src/api"
    ports:
      - "${PORT}:${PORT}"
    networks:
        - api-net
    command: npm run dev 
  db:
    image: mysql
    container_name: mysql_portafolio
    networks:
      - api-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_USER: ${DB_USER} 
      MYSQL_DATABASE: ${DB_DATABASE} 
      MYSQL_PASSWORD: ${DB_PASSWORD} 
    
networks:
  api-net:
    driver: bridge
